### ISSUE TITLE
Remove "x" on tracks.

### ISSUE THREAD

**Issue by jstnjns** [jstnjns/cloudlist#1]
There's no need to delete tracks.  Kill the "x", and the code that powers it.

**Comment by mattgoucher** [comment]
No need to delete? Can't remove something from the queue once it's added?

**Comment by jstnjns** [comment]
Skipping a track will mark it as "listened to" which will make it pretty much the same as deleted.

**Comment by stephenp** [comment]
Thought about this more, and until the "moving / autoadvancing" playlist works, we still need the delete x's so we can clear out the queue
