### ISSUE TITLE
Introduce Shuffle Feature

### ISSUE THREAD

**Issue by merittthomas** [jstnjns/cloudlist#13]
![untitled-1](https://cloud.githubusercontent.com/assets/4406551/6653398/6ac11772-ca4e-11e4-99eb-cec18d64f1d2.png)

**Comment by jstnjns** [comment]
Shuffle and Repeat (one)

![screen shot 2015-03-17 at 11 45 21 pm](https://cloud.githubusercontent.com/assets/249444/6703953/be347a76-ccff-11e4-9344-faba41fe9e55.png)
