### ISSUE TITLE
Add in soundcloud url

### ISSUE THREAD

**Issue by stephenp** [jstnjns/cloudlist#4]
Looks like we only get back the api url?  Can we get back the vanilla soundcloud url so we can link out to it from our app?

**Comment by jstnjns** [comment]
Yea.  So, I'm going to do a hybrid of what we talked about the other day.  The URL right now that we store for the track is the stream url needed to actually play.  But I will be storing the entirety of data we get back from SoundCloud (when adding the track) as `meta`.  Then we will have access to things like the permalink and other info.

**Comment by stephenp** [comment]
Done!  We now store the soundcloud response as meta, and I've implemented a link out to soundcloud for new tracks moving forward.
