### ISSUE TITLE
"Listened" track indicator

### ISSUE THREAD

**Issue by merittthomas** [jstnjns/cloudlist#6]
Some way to easily tell which tracks you have already listened to (and which ones you haven't).

Maybe just apply an `opacity: 0.6;`?

(Will probably have to be implemented after 'Users')...

![untitled-9](https://cloud.githubusercontent.com/assets/4406551/6492612/cf0a335e-c269-11e4-8df3-41a22c10b574.png)

**Comment by jstnjns** [comment]
After users, "listened to" tracks will be removed from the list altogether and added to the archive.
